runtime: nodejs22
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_instances: 1
  min_instances: 1
entrypoint: node --env-file=.env.production dist/src/index.js
env_variables:
  NODE_ENV: "production"
handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301
