runtime: nodejs22
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_instances: 1
  min_instances: 1
handlers:
  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301
readiness_check:
  path: "/api/v1"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 30
