# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Google App Engine CI/CD

on:
  push:
    branches: [ "main", "gcloud" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup Production Environment
      # openssl base64 -A -in .env.production -out .env.production.vault
      run: echo "${{secrets.ENV_PRODUCTION}}" | openssl base64 -A -d > server/.env.production
    - name: Install and Build
      run: |
        cd server
        npm install
        npm run build
    - id: 'auth'
      name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{secrets.GCLOUD_SERVICE_KEY_JSON}}
    - id: 'deploy'
      name: Google App Engine
      uses: google-github-actions/deploy-appengine@v2
      if: ${{ hashFiles('server/.env.production') != '' }}
      with:
        working_directory: ./server
        project_id: ${{secrets.GOOGLE_PROJECT_ID}}
        version: v1
        flags: --no-cache
        deliverables: app.yaml
